spring:
  application:
    name: JobSearchPlatform

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:job_search_platform}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true

server:
  port: ${SERVER_PORT:8081}

logging:
  file:
    path: logs
  level:
    root: INFO
    org.example.jobsearchplatform: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.stat: WARN

app:
  async:
    demo-delay-ms: 16000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
